services:
  - type: web
    name: telegram-downloader-bot
    runtime: docker
    plan: free
    region: oregon

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: INSTAGRAM_USERNAME
        sync: false
      - key: INSTAGRAM_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8080"

    healthCheckPath: /