import os
import uuid
import json
import logging
import yt_dlp

logger = logging.getLogger(__name__)
DOWNLOAD_DIR = os.path.join(os.path.dirname(__file__), "../../downloads")
os.makedirs(DOWNLOAD_DIR, exist_ok=True)

COOKIES_FILE = os.path.join(os.path.dirname(__file__), "../../ig_cookies.txt")
COOKIES_NETSCAPE = os.path.join(os.path.dirname(__file__), "../../ig_cookies_netscape.txt")

IG_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/125.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.instagram.com/",
    "Origin": "https://www.instagram.com",
}


def _convert_json_cookies_to_netscape(json_path: str, netscape_path: str):
    """Convert EditThisCookie JSON format to Netscape format that yt-dlp understands."""
    with open(json_path, "r", encoding="utf-8") as f:
        cookies = json.load(f)

    lines = ["# Netscape HTTP Cookie File", "# Generated by telegram-downloader-bot", ""]

    for c in cookies:
        domain = c.get("domain", ".instagram.com")
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expirationDate", 0))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

    with open(netscape_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    logger.info(f"Converted {len(cookies)} cookies to Netscape format")


def _get_cookies_file() -> str | None:
    """Get the right cookies file, converting from JSON if needed."""
    if not os.path.exists(COOKIES_FILE):
        return None

    # Check if it's JSON format
    with open(COOKIES_FILE, "r", encoding="utf-8") as f:
        content = f.read().strip()

    if content.startswith("["):
        # It's JSON — convert to Netscape
        logger.info("Converting JSON cookies to Netscape format...")
        _convert_json_cookies_to_netscape(COOKIES_FILE, COOKIES_NETSCAPE)
        return COOKIES_NETSCAPE
    else:
        # Already Netscape format
        return COOKIES_FILE


def _base_opts(uid: str, cookies_path: str | None) -> dict:
    opts = {
        "outtmpl": os.path.join(DOWNLOAD_DIR, f"ig_{uid}.%(ext)s"),
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best",
        "merge_output_format": "mp4",
        "http_headers": IG_HEADERS,
        "socket_timeout": 30,
        "retries": 3,
    }
    if cookies_path:
        opts["cookiefile"] = cookies_path
        logger.info(f"Using cookies: {cookies_path}")
    return opts


def download_instagram(url: str) -> str:
    uid = str(uuid.uuid4())[:8]
    cookies_path = _get_cookies_file()
    clean_url = url.split("?")[0].rstrip("/") + "/"

    logger.info(f"Instagram download | url={clean_url} | cookies={'yes' if cookies_path else 'no'}")

    # Attempt 1: clean URL with cookies
    try:
        return _do_download(_base_opts(uid, cookies_path), clean_url, uid)
    except Exception as e:
        logger.warning(f"IG attempt 1 failed: {e}")

    # Attempt 2: original URL with cookies
    try:
        return _do_download(_base_opts(uid, cookies_path), url, uid)
    except Exception as e:
        logger.warning(f"IG attempt 2 failed: {e}")

    # Attempt 3: format=best fallback
    try:
        opts = _base_opts(uid, cookies_path)
        opts["format"] = "best"
        return _do_download(opts, clean_url, uid)
    except Exception as e:
        logger.warning(f"IG attempt 3 failed: {e}")

    raise Exception("instagram_failed")


def _do_download(ydl_opts: dict, url: str, uid: str) -> str:
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        if info.get("_type") == "playlist":
            entries = info.get("entries", [])
            if entries:
                info = entries[0]
        filename = ydl.prepare_filename(info)

    base = os.path.splitext(filename)[0]
    for ext in ["mp4", "webm", "mkv", "mov", "m4v"]:
        candidate = f"{base}.{ext}"
        if os.path.exists(candidate):
            return candidate

    for f in sorted(
        os.listdir(DOWNLOAD_DIR),
        key=lambda x: os.path.getmtime(os.path.join(DOWNLOAD_DIR, x)),
        reverse=True
    ):
        if uid in f:
            return os.path.join(DOWNLOAD_DIR, f)

    raise FileNotFoundError(f"Instagram file not found for uid {uid}")